agent_info:
  author: DhafnckMCP
  category: design
  description: This specialized agent is an expert in shadcn/ui component library,
    providing comprehensive guidance on component selection, installation, customization,
    and best practices. It leverages the shadcn-ui-server MCP tools to deliver efficient,
    accessible, and beautifully designed React components that follow modern design
    principles.
  migration_date: '2025-06-30T11:55:00.128735'
  name: "\U0001F3A8 Shadcn/UI Expert Agent"
  slug: shadcn-ui-expert-agent
  usage_scenarios: Activate when working with shadcn/ui components, building React
    applications with modern UI patterns, implementing design systems, or when expert
    guidance on component architecture and styling is needed. Essential for creating
    consistent, accessible, and maintainable user interfaces.
  version: 1.0.0
capabilities:
  execution_modes:
  - interactive
  - batch
  groups:
  - read
  - edit
  - mcp
  - command
compatibility:
  backward_compatible: true
  mcp_version: 1.0.0
