services:
  dhafnck-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: runtime
    image: dhafnck/mcp-server:latest
    container_name: dhafnck-mcp-server
    restart: unless-stopped
    
    # Port mapping for HTTP MCP server
    ports:
      - "8000:8000"
    
    # Default command (stdio mode for MCP)
    # command: ["python", "-m", "fastmcp.server.mcp_entry_point"]
    
    # Environment variables
    environment:
      # Core MCP Configuration
      - PYTHONPATH=/app/src
      - FASTMCP_LOG_LEVEL=INFO
      - FASTMCP_ENABLE_RICH_TRACEBACKS=0
      
      # Data Storage Configuration
      - DATA_STORAGE_MODE=${DATA_STORAGE_MODE:-internal}
      
      # Task Management Paths
      - TASKS_JSON_PATH=/data/tasks
      - PROJECTS_FILE_PATH=/data/projects/projects.json
      - CURSOR_RULES_DIR=/app/rules
      - AGENT_LIBRARY_DIR_PATH=/app/agent-library
      
      # Authentication Configuration
      - DHAFNCK_AUTH_ENABLED=${DHAFNCK_AUTH_ENABLED:-true}
      - DHAFNCK_MVP_MODE=${DHAFNCK_MVP_MODE:-false}
      
      # Supabase Configuration (Optional - set in .env file)
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
      - DHAFNCK_TOKEN=${DHAFNCK_TOKEN:-}
      
      # HTTP Transport Configuration
      - FASTMCP_TRANSPORT=streamable-http
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
    
    # Volume mounts for data persistence
    volumes:
      # Data persistence
      - dhafnck_data:/data
      - dhafnck_logs:/app/logs
      
      # Configuration files (optional - for advanced users)
      - ./config:/app/config:ro
      
      # Development mode: mount source code (comment out for production)
      # - ./src:/app/src:ro  # Commented out for self-contained container
    
    # Health check for HTTP mode (check if port is listening)
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # User specification (matches Dockerfile)
    # user: "1000:1000"  # Disabled for permission fix
    
    # Network mode for MCP (typically stdio, but HTTP available)
    # network_mode: "bridge"

# Named volumes for data persistence
volumes:
  dhafnck_data:
    driver: local
  
  dhafnck_logs:
    driver: local 